name: Bundle dependencies

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "00 04 * * *"

jobs:
  get-versions:
    uses: ./.github/workflows/manifest.yml
    with:
      config-path: manifest.json

  build-all-deps:
    needs: get-versions
    env:
      DIFFUTILS_VERSION: ${{needs.get-versions.outputs.DIFFUTILS_VERSION}}
      GETTEXT_VERSION: ${{needs.get-versions.outputs.GETTEXT_VERSION}}
      ICU_VERSION: ${{needs.get-versions.outputs.ICU_VERSION}}
      KRB5_VERSION: ${{needs.get-versions.outputs.KRB5_VERSION}}
      LIBICONV_VERSION: ${{needs.get-versions.outputs.LIBICONV_VERSION}}
      LIBXML2_VERSION: ${{needs.get-versions.outputs.LIBXML2_VERSION}}
      LIBXSLT_VERSION: ${{needs.get-versions.outputs.LIBXSLT_VERSION}}
      LZ4_VERSION: ${{needs.get-versions.outputs.LZ4_VERSION}}
      MESON_VERSION: ${{needs.get-versions.outputs.MESON_VERSION}}
      NINJA_VERSION: ${{needs.get-versions.outputs.NINJA_VERSION}}
      OPENSSL_VERSION: ${{needs.get-versions.outputs.OPENSSL_VERSION}}
      OSSP-UUID_VERSION: ${{needs.get-versions.outputs.OSSP-UUID_VERSION}}
      PKGCONF_VERSION: ${{needs.get-versions.outputs.PKGCONF_VERSION}}
      WINFLEXBISON_VERSION: ${{needs.get-versions.outputs.WINFLEXBISON_VERSION}}
      ZLIB_VERSION: ${{needs.get-versions.outputs.ZLIB_VERSION}}
      ZSTD_VERSION: ${{needs.get-versions.outputs.ZSTD_VERSION}}
      
        
    runs-on: windows-latest
    steps:
      - name: Download diffutils
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: diffutils.yml
          workflow_conclusion: success
          name: diffutils-${{ env.DIFFUTILS_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download gettext
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: gettext.yml
          workflow_conclusion: success
          name: gettext-${{ env.GETTEXT_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download icu
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: icu.yml
          workflow_conclusion: success
          name: icu-${{ env.ICU_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download krb5
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: krb5.yml
          workflow_conclusion: success
          name: krb5-${{ env.KRB5_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download libiconv
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: libiconv.yml
          workflow_conclusion: success
          name: libiconv-${{ env.LIBICONV_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download libxml2
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: libxml2.yml
          workflow_conclusion: success
          name: libxml2-${{ env.LIBXML2_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download libxslt
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: libxslt.yml
          workflow_conclusion: success
          name: libxslt-${{ env.LIBXSLT_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download lz4
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: lz4.yml
          workflow_conclusion: success
          name: lz4-${{ env.LZ4_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download meson
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: meson.yml
          workflow_conclusion: success
          name: meson-${{ env.MESON_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download ninja
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ninja.yml
          workflow_conclusion: success
          name: ninja-${{ env.NINJA_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download openssl
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: openssl.yml
          workflow_conclusion: success
          name: openssl-${{ env.OPENSSL_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download ossp-uuid
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ossp-uuid.yml
          workflow_conclusion: success
          name: ossp-uuid-${{ env.OSSP-UUID_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download pkgconf
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pkgconf.yml
          workflow_conclusion: success
          name: pkgconf-${{ env.PKGCONF_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download winflexbison
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: winflexbison.yml
          workflow_conclusion: success
          name: winflexbison-${{ env.WINFLEXBISON_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download zlib
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: zlib.yml
          workflow_conclusion: success
          name: zlib-${{ env.ZLIB_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      - name: Download zstd
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: zstd.yml
          workflow_conclusion: success
          name: zstd-${{ env.ZSTD_VERSION }}-win64
          path: /builddeps
          if_no_artifact_found: fail

      # github errors out due to too many files :(
      - name: Remove docs
        run: |
          rm.exe -rf `
              \builddeps\share\docs `
              \builddeps\mesonbuild\docs `
              "\builddeps\mesonbuild\test cases" `
              \builddeps\html

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: all-deps-win64
          path: /builddeps

      - name: Package Release Assets
        shell: pwsh
        run: |
          Compress-Archive /builddeps /postgresql-dependencies-latest.zip
          
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dependencies-latest"
          title: "PostgreSQL Dependencies"
          files: |
            /postgresql-dependencies-latest.zip
