name: Bundle dependencies

on:
  workflow_dispatch:
  workflow_call:

jobs:
  get-versions:
    uses: ./.github/workflows/manifest.yml
    with:
      config-path: manifest.json

  build-all-deps:
    needs: get-versions
    env:
      DIFFUTILS_VERSION: ${{needs.get-versions.outputs.DIFFUTILS_VERSION}}
      GETTEXT_VERSION: ${{needs.get-versions.outputs.GETTEXT_VERSION}}
      ICU_VERSION: ${{needs.get-versions.outputs.ICU_VERSION}}
      KRB5_VERSION: ${{needs.get-versions.outputs.KRB5_VERSION}}
      LIBICONV_VERSION: ${{needs.get-versions.outputs.LIBICONV_VERSION}}
      LIBXML2_VERSION: ${{needs.get-versions.outputs.LIBXML2_VERSION}}
      LIBXSLT_VERSION: ${{needs.get-versions.outputs.LIBXSLT_VERSION}}
      LZ4_VERSION: ${{needs.get-versions.outputs.LZ4_VERSION}}
      MESON_VERSION: ${{needs.get-versions.outputs.MESON_VERSION}}
      NINJA_VERSION: ${{needs.get-versions.outputs.NINJA_VERSION}}
      OPENSSL_VERSION: ${{needs.get-versions.outputs.OPENSSL_VERSION}}
      OSSP-UUID_VERSION: ${{needs.get-versions.outputs.OSSP-UUID_VERSION}}
      PKGCONF_VERSION: ${{needs.get-versions.outputs.PKGCONF_VERSION}}
      WINFLEXBISON_VERSION: ${{needs.get-versions.outputs.WINFLEXBISON_VERSION}}
      ZLIB_VERSION: ${{needs.get-versions.outputs.ZLIB_VERSION}}
      ZSTD_VERSION: ${{needs.get-versions.outputs.ZSTD_VERSION}}
      
        
    runs-on: windows-latest
    steps:
      - name: Download diffutils
        uses: actions/download-artifact@v7
        with:
          name: diffutils-${{ env.DIFFUTILS_VERSION }}-win64
          path: /builddeps

      - name: Download gettext
        uses: actions/download-artifact@v7
        with:
          name: gettext-${{ env.GETTEXT_VERSION }}-win64
          path: /builddeps

      - name: Download icu
        uses: actions/download-artifact@v7
        with:
          name: icu-${{ env.ICU_VERSION }}-win64
          path: /builddeps

      - name: Download krb5
        uses: actions/download-artifact@v7
        with:
          name: krb5-${{ env.KRB5_VERSION }}-win64
          path: /builddeps

      - name: Download libiconv
        uses: actions/download-artifact@v7
        with:
          name: libiconv-${{ env.LIBICONV_VERSION }}-win64
          path: /builddeps

      - name: Download libxml2
        uses: actions/download-artifact@v7
        with:
          name: libxml2-${{ env.LIBXML2_VERSION }}-win64
          path: /builddeps

      - name: Download libxslt
        uses: actions/download-artifact@v7
        with:
          name: libxslt-${{ env.LIBXSLT_VERSION }}-win64
          path: /builddeps

      - name: Download lz4
        uses: actions/download-artifact@v7
        with:
          name: lz4-${{ env.LZ4_VERSION }}-win64
          path: /builddeps

      - name: Download meson
        uses: actions/download-artifact@v7
        with:
          name: meson-${{ env.MESON_VERSION }}-win64
          path: /builddeps

      - name: Download ninja
        uses: actions/download-artifact@v7
        with:
          name: ninja-${{ env.NINJA_VERSION }}-win64
          path: /builddeps

      - name: Download openssl
        uses: actions/download-artifact@v7
        with:
          name: openssl-${{ env.OPENSSL_VERSION }}-win64
          path: /builddeps

      - name: Download ossp-uuid
        uses: actions/download-artifact@v7
        with:
          name: ossp-uuid-${{ env.OSSP-UUID_VERSION }}-win64
          path: /builddeps

      - name: Download pkgconf
        uses: actions/download-artifact@v7
        with:
          name: pkgconf-${{ env.PKGCONF_VERSION }}-win64
          path: /builddeps

      - name: Download winflexbison
        uses: actions/download-artifact@v7
        with:
          name: winflexbison-${{ env.WINFLEXBISON_VERSION }}-win64
          path: /builddeps

      - name: Download zlib
        uses: actions/download-artifact@v7
        with:
          name: zlib-${{ env.ZLIB_VERSION }}-win64
          path: /builddeps

      - name: Download zstd
        uses: actions/download-artifact@v7
        with:
          name: zstd-${{ env.ZSTD_VERSION }}-win64
          path: /builddeps

      # github errors out due to too many files :(
      - name: Remove docs
        run: |
          rm.exe -rf `
              \builddeps\share\docs `
              \builddeps\mesonbuild\docs `
              "\builddeps\mesonbuild\test cases" `
              \builddeps\html

      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: all-deps-win64
          path: /builddeps

      - name: Package Release Assets
        shell: pwsh
        run: |
          Compress-Archive /builddeps /postgresql-dependencies-latest.zip
          
      - name: Delete Existing Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "dependencies-latest" --repo "${{ github.repository }}" --cleanup-tag --yes || true

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "dependencies-latest"
          target_commitish: ${{ github.sha }}
          name: "PostgreSQL Dependencies"
          prerelease: true
          files: |
            /postgresql-dependencies-latest.zip
